language: php
#sudo: required

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  fast_finish: true

#addons:
#  hosts:
#    - api.openweathermap.org

#before_install:
#  - sudo apt-get -qq update
#  - sudo apt-get install -y socat
#  - cat /etc/hosts
#  - sudo socat TCP-LISTEN:80,fork TCP:${RTCP_HOST}:${RTCP_PORT} > /tmp/socat.log 2>&1 &

install:
  - composer install

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
