dist: trusty
sudo: false

language: php

matrix:
  include:
    - php: nightly
    - php: 7.4
    - php: 7.3
    - php: 7.2
    - php: 7.1
    - php: 7.0
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  directories:
    - "$HOME/.composer/cache"

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - INI_FILE=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo date.timezone = Europe/Berlin >> $INI_FILE
  - echo memory_limit = -1 >> $INI_FILE

install:
  # Use composer update instead of composer install to install a working set of
  # dependencies on all PHP versions.
  - composer update --prefer-dist --prefer-stable

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml

after_success:
  # Scrutinizer
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml
  # CodeCov
  - bash <(curl -s https://codecov.io/bash)
